# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.
# Mend Containers will automatically pull the container defined and scan for open source components. 

name: Mend CLI Scan

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      ## Maven example - replace with your build steps
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      ##
    - name: Mend CLI Scan
      # The Mend SCA CLI scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
      env:
        #SCA
        MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
        MEND_URL: https://app.whitesourcesoftware.com
        #SAST
      #MEND_SAST_SERVER_URL: https://saas.mend.io/sast
      #MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
      #MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
      run: |
        echo Downloading Mend CLI
        curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
        echo Start Mend CLI scan
        ./mend sca -u
      #  ./mend sast

# Runs a single command using the runners shell
#- name: Run a one-line script
#  run: echo Hello, world!

# Runs a set of commands using the runners shell
#- name: Run a multi-line script
#  run: |
#    echo Add other actions to build,
#    echo test, and deploy your project.
